# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')
# Restaurant.create!(name: "Hasinakhatoon",restaurant_name:"7 days",email:"hasina@gmail.com",image: "",phone:"732467657")
# Restaurant.create!(name: "Arti",restaurant_name:"crown plaza",email:"arti@gmail.com",image: "",phone:"732467657")
# Restaurant.create!(name: "Ankit",restaurant_name:"5star",email:"ankit@gmail.com",image: "",phone:"732467657")
# Restaurant.create!(name: "rahul",restaurant_name:"taj",email:"rahul@gmail.com",image: "",phone:"732467657")
# Chef.create!(name:"jai",email:"jai@gmail.com",restaurant_id:"1",image:"",phone:"43534866785")
# Chef.create!(name:"arti",email:"arti@gmail.com",restaurant_id:"1",image:"",phone:"43534866785")
# Chef.create!(name:"mayank",email:"mayank@gmail.com",restaurant_id:"1",image:"",phone:"43534866785")
# Chef.create!(name:"shekhar",email:"shekhar@gmail.com",restaurant_id:"1",image:"",phone:"43534866785")
# Chef.create!(name:"rohan",email:"rohan@gmail.com",restaurant_id:"1",image:"",phone:"43534866785")
# Chef.create!(name:"jai",email:"jai@gmail.com",restaurant_id:"2",image:"",phone:"43534866785")
# Chef.create!(name:"hasina",email:"hasina@gmail.com",restaurant_id:"2",image:"",phone:"43534866785")
# Chef.create!(name:"rohan",email:"rohan@gmail.com",restaurant_id:"2",image:"",phone:"43534866785")
# Chef.create!(name:"mayank",email:"mayank@gmail.com",restaurant_id:"2",image:"",phone:"43534866785")
# Chef.create!(name:"shekhar",email:"shekhar@gmail.com",restaurant_id:"2",image:"",phone:"43534866785")
# Chef.create!(name:"jai",email:"jai@gmail.com",restaurant_id:"3",image:"",phone:"43534866785")
# Chef.create!(name:"hasina",email:"hasina@gmail.com",restaurant_id:"3",image:"",phone:"43534866785")
# Chef.create!(name:"rohan",email:"rohan@gmail.com",restaurant_id:"3",image:"",phone:"43534866785")
# Chef.create!(name:"mayank",email:"mayank@gmail.com",restaurant_id:"3",image:"",phone:"43534866785")
# Chef.create!(name:"mayank",email:"mayank@gmail.com",restaurant_id:"4",image:"",phone:"43534866785")
# Chef.create!(name:"rohan",email:"rohan@gmail.com",restaurant_id:"4",image:"",phone:"43534866785")
# Chef.create!(name:"arti",email:"arti@gmail.com",restaurant_id:"4",image:"",phone:"43534866785")
# Chef.create!(name:"hasina",email:"hasina@gmail.com",restaurant_id:"4",image:"",phone:"43534866785")
# Chef.create!(name:"shekhar",email:"shekhar@gmail.com",restaurant_id:"4",image:"",phone:"43534866785")
# Product.create!(name:"Potato chips",restaurant_id:"1")
# Product.create!(name:"lay's chips",restaurant_id:"1")
# Product.create!(name:"dairy milk",restaurant_id:"1")
# Product.create!(name:"Good day",restaurant_id:"1")
# Product.create!(name:"kurkure",restaurant_id:"3")
# Product.create!(name:"dream light",restaurant_id:"3")
# ProductIngredient.create!(product_id:1,ingredient_id: 50)
# ProductIngredient.create!(product_id:1,ingredient_id: 51)
# ProductIngredient.create!(product_id:1,ingredient_id: 52)
# ProductIngredient.create!(product_id:1,ingredient_id: 57)
# ProductIngredient.create!(product_id:1,ingredient_id: 59)
# ProductIngredient.create!(product_id:1,ingredient_id: 69)
# ProductIngredient.create!(product_id:1,ingredient_id: 60)
# ProductIngredient.create!(product_id:1,ingredient_id: 65)
# ProductIngredient.create!(product_id:1,ingredient_id: 89)
# ProductIngredient.create!(product_id:1,ingredient_id: 58)
# ProductIngredient.create!(product_id:1,ingredient_id: 67)
# ProductIngredient.create!(product_id:1,ingredient_id: 500)
# ProductIngredient.create!(product_id:1,ingredient_id: 501)
# ProductIngredient.create!(product_id:1,ingredient_id: 502)
# ProductIngredient.create!(product_id:1,ingredient_id: 589)
# ProductIngredient.create!(product_id:1,ingredient_id: 345)
# ProductIngredient.create!(product_id:1,ingredient_id: 300)
# ProductIngredient.create!(product_id:1,ingredient_id: 234)
# ProductIngredient.create!(product_id:1,ingredient_id: 200)
# ProductIngredient.create!(product_id:1,ingredient_id: 457)
# ProductIngredient.create!(product_id:1,ingredient_id: 45)
# ProductIngredient.create!(product_id:1,ingredient_id: 123)
# ProductIngredient.create!(product_id:1,ingredient_id: 356)
# ProductIngredient.create!(product_id:1,ingredient_id: 600)
# ProductIngredient.create!(product_id:1,ingredient_id: 678)
# ProductIngredient.create!(product_id:1,ingredient_id: 234)
# ProductIngredient.create!(product_id:1,ingredient_id: 400)
# ProductIngredient.create!(product_id:1,ingredient_id: 492)
# ProductIngredient.create!(product_id:1,ingredient_id: 451)








